### ISSUE TITLE
[Feature Request] Disable wallpaper option

### ISSUE THREAD

**Issue by Leplik500** [doki-theme/doki-theme-jupyter#15]
Hello, please give a user opportunity to disable background wallpaper and replace it with a solid theme background color just like in other IDEs. I like wallpapers, but i feel it really worsens readability and focus.

**Comment by Unthrottled** [comment]
![Heresy](https://i.kym-cdn.com/photos/images/facebook/000/691/973/e75.jpg)


For real though, I'll add it. Might have time this weekend to add it.

**Comment by Unthrottled** [comment]
Alright, I've added this option, you should be able to update the [Doki Theme for Jupyter to v88.1.1.1.0](https://pypi.org/project/doki-theme-jupyter/88.1.1.1.0/), thanks!
